version: '2'
services:
        converter:
                build: 
                        context: ./
                        args:
                                - http_proxy=${http_proxy}
                volumes: 
                        - ./:/workdir
                command: sh convert.sh
